Validate presence of AstraZeneca gene panels
callachennault/cmo-pipelines pull request #4
Opened 2024-05-24 18:23 UTC by jamesqo

2024-05-24 18:45 UTC, callachennault reviewed
great work @jamesqo! I left a few comments we can talk through over zoom

2024-05-24 18:45 UTC, callachennault commented on import-scripts/validation_utils_py3.py
> +        header, df = self.load_file("data_clinical_sample.txt", parse_header=True)
imo the df should be stored in the class so it can be used for different checks without re-reading

2024-05-24 18:45 UTC, callachennault commented on import-scripts/validation_utils_py3.py
> +        self.write_to_file("data_clinical_sample.txt", df, header=header)
I also don't want the file to be re-written on each check - this is what the old validation_utils does and leads to inefficiencies when you're validating multiple checks on the same file

2024-05-24 18:45 UTC, callachennault commented on import-scripts/validation_utils_py3.py
> +        df = self.load_file("data_gene_matrix.txt")
same thing as my earlier comment - I think this should be stored somewhere in the class

2024-05-24 18:45 UTC, callachennault commented on import-scripts/validation_utils_py3.py
> +        help="Path to study directory",
I think changing this to a study dir makes sense but I wonder if we should allow flexibility for file names that might be different than we expect

2024-05-24 18:45 UTC, callachennault commented on import-scripts/validation_utils_py3.py
>  As of 5/14/24 only CDM clinical sample file validation has been implemented but
can update this comment

2024-05-24 18:45 UTC, callachennault commented on import-scripts/validation_utils_py3.py
> +            file_path,
I had added output_file_path as an option to allow flexibility for situations where we might not want to immediately rewrite the input file / make testing easier

2024-05-29 02:46 UTC, jamesqo commented on import-scripts/validation_utils_py3.py
>  As of 5/14/24 only CDM clinical sample file validation has been implemented but
done

2024-05-29 02:47 UTC, jamesqo commented on import-scripts/validation_utils_py3.py
> +            file_path,
You're right, I added an extra parameter to allow writing to a different file.

2024-05-29 02:48 UTC, jamesqo commented on import-scripts/validation_utils_py3.py
> +        help="Path to study directory",
We discussed this on Friday-- if it comes to that we can use something like the case_list_config.tsv as the masterlist of all acceptable names.

2024-05-29 02:49 UTC, jamesqo commented on import-scripts/validation_utils_py3.py
> +        self.write_to_file("data_clinical_sample.txt", df, header=header)
Discussed this Friday-- in such cases we will have a nested function like

```
def check_sample_file():
    df = load_sample_file()

    @check
    def fn1():

    @check
    def fn2():
```

2024-05-29 13:54 UTC, jamesqo commented
Hey @callachennault, I updated the PR in response to your feedback-- you can take another look and merge if you want. The remaining things to be done are:

- [ ] Decide if/where to generate report files. Right now, it's being generated under `validation_reports/report.json` for AZ, and it's not being written out for CDM.
- [ ] Test that the AZ import script calls into validation_utils correctly
- [ ] Test that the CDM import script calls into validation_utils correctly

2024-05-31 18:22 UTC, callachennault requested changes
lgtm, just left a few small change requests

2024-05-31 18:22 UTC, callachennault commented on import-scripts/test-py3/test_az_validation.py
> +    def test_gene_panel_missing(self):
I would add a base-case test for a no-error case (all gene panels are present)

2024-05-31 18:22 UTC, callachennault commented on import-scripts/test-py3/resources/validation_utils/az_gene_panel/missing_panels/data_gene_matrix.txt
> +P-0002221-T03-IM6	IMPACT468	IMPACT468	IMPACT468
Would recommend using a smaller + anonymized test file

2024-05-31 18:22 UTC, callachennault commented on import-scripts/update-az-mskimpact.sh
> +    REPORT_DIR="$AZ_MSK_IMPACT_DATA_HOME/validation_reports"
I think we could write the output to /data/portal-cron/logs or make a dir under /data/portal-cron/tmp (we write logs for other ad-hoc scripts here). Avery has recommended we try out datadog integration too

2024-06-05 20:00 UTC, jamesqo commented on import-scripts/update-az-mskimpact.sh
> +    REPORT_DIR="$AZ_MSK_IMPACT_DATA_HOME/validation_reports"
I'm going to have it output to a file in /data/portal-cron/logs. Datadog integration can be done independently of the script by tailing the log file-- that will be done separately of this PR.

2024-06-05 20:13 UTC, jamesqo commented on import-scripts/validation_utils_py3.py
> +    LOG_FILE = "/data/portal-cron/logs/validation_utils_py3.log"
@callachennault I hard-coded this path, but if you have a better way to organize it feel free to change the code

2024-06-14 15:43 UTC, merged